# Configuración básica
spring.application.name=JAKASTYLE
server.port=5000

# Base de datos
spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres?user=postgres.ncyuduzftdsuatpyjwnf&password=lostiracodigo
spring.datasource.username=postgres.wmnzzreruellnxowxvbm
spring.datasource.password=lostiracodigo
spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
spring.mvc.hiddenmethod.filter.enabled=true
spring.datasource.hikari.maximum-pool-size=40
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
logging.level.org.springframework.transaction=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Usa una de estas opciones:
file.upload-dir=${user.home}/jakastyle_uploads/
